[18.0][MIG] mgmtsystem_nonconformity: Migration to 18.0
natuan9/management-system pull request #3
Opened 2024-11-06 08:29 UTC by natuan9

**Depend on:**
- [[18.0][MIG] document_page_procedure: Migration to 18.0](https://github.com/natuan9/management-system/pull/1)
- `[[18.0][MIG] mgmtsystem_action: Migration to 18.0 ](https://github.com/OCA/management-system/pull/605)`

**Ported from v14:**
- `#525`

**Change in v18:**
 - `[remove order parameter of group_expand methods](https://github.com/odoo/odoo/pull/139294/commits/6e6bcbc6ab5cef679b17b617d821b2bb3f778af8) `

2024-11-08 05:02 UTC, thienvh332 requested changes

2024-11-08 05:02 UTC, thienvh332 commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_abstract.py
> +    # TODO: Remove this on 17.0 and move everything on mail.thread
Get it done bro :wink:

2024-11-08 05:02 UTC, thienvh332 commented on mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
> +            <kanban
Edit the kanban view
![image](https://github.com/user-attachments/assets/3bd9731c-8688-4c0c-a366-95d174088ffa)

2024-11-08 05:02 UTC, thienvh332 commented on mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
> +                            </div>
Do we still need it?

2024-11-08 05:02 UTC, thienvh332 commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_abstract.py
> +        readonly=True,
If a field is marked as readonly=True on the model, it won't be possible to import it through the Odoo import tool, so avoid it as possible and define the readonly attribute on the views instead.
```suggestion
```

2024-11-08 05:02 UTC, thienvh332 commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +    closing_date = fields.Datetime(readonly=True)
Same here

2024-11-08 05:02 UTC, thienvh332 commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +        readonly=True,
Same here. Let's fix it all :wink:

2024-11-15 09:31 UTC, natuan9 commented
Hi a @thienvh332 , Please help to review PR again

**Kanban Migration**
- Version 17.0
![image](https://github.com/user-attachments/assets/944f2a80-e366-4032-bead-110d0679e073)

- Version 18.0
![image](https://github.com/user-attachments/assets/996fe9bb-2821-47be-b568-22bfa15599a2)

2024-11-20 09:35 UTC, thienvh332 commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> -    def _stage_groups(self, stages, domain, order):
Is there any reason for this removal?

2024-11-20 09:35 UTC, thienvh332 commented on mgmtsystem_nonconformity/reports/mgmtsystem_nonconformity_report.xml
> +                <field name="number_of_nonconformities" type="measure" />
```suggestion
                <field name="number_of_nonconformities" type="measure" readonly="True"  />
```

2024-11-20 09:35 UTC, thienvh332 commented on mgmtsystem_nonconformity/reports/mgmtsystem_nonconformity_report.xml
> +                <field name="number_of_nonconformities" type="measure" />
```suggestion
                <field name="number_of_nonconformities" type="measure" readonly="True"  />
```

2024-11-20 09:35 UTC, thienvh332 commented on mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
> +                <field name="ref" readonly="1" />
```suggestion
                <field name="ref" readonly="True" />
```

2024-11-20 09:42 UTC, natuan9 commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> -    def _stage_groups(self, stages, domain, order):
order parameter of group_expand methods is remove
you can see the detail here `https://github.com/odoo/odoo/pull/139294/commits/6e6bcbc6ab5cef679b17b617d821b2bb3f778af8`

2024-11-20 09:53 UTC, thienvh332 commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_cause.py
> +    parent_path = fields.Char(index=True, unaccent=False)
Remove **`unaccent`** in all fields. It is not necessary anymore.

2024-11-20 09:58 UTC, thienvh332 commented on mgmtsystem_nonconformity/views/mgmtsystem_origin.xml
> +                    <field name="active" invisible="1" />
```suggestion

```

2024-11-20 09:58 UTC, thienvh332 commented on mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
> +                    <field name="state" invisible="True" />
```suggestion

```

2024-11-20 10:18 UTC, thienvh332 commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_origin.py
> +    parent_path = fields.Char(index=True, unaccent=False)
Remove here

2024-11-20 10:27 UTC, thienvh332 approved these changes
LGTM

2024-12-26 03:24 UTC, closed without merging